from SCons.Environment import Environment
from build_scripts.utility import GlobRecursive


Import('TARGET_ENVIRONMENT')
TARGET_ENVIRONMENT: Environment

env = TARGET_ENVIRONMENT.Clone()
env.Append(
    CPPPATH = [ 
        env.Dir('.').srcnode(),
    ],
    ASFLAGS = [ '-I', env.Dir('.').srcnode(), '-f', 'elf' ]
)

sources = GlobRecursive(env, '*.c') + \
          GlobRecursive(env, '*.cpp') + \
          GlobRecursive(env, '*.asm')

objects = env.Object(sources)

libc = env.StaticLibrary('libc.o', objects)

Export('libc')